outputs are for small vars, files for diffs

diff --git a/.github/workflows/osl_check.yml b/.github/workflows/osl_check.yml
--- a/.github/workflows/osl_check.yml
+++ b/.github/workflows/osl_check.yml
@@ -8,7 +8,7 @@ jobs:
     runs-on: ubuntu-latest
 
     outputs:
-      diff_of_diffs: ${{ steps.diffCollector.outputs.diff_of_diffs }}
+      needs_osl: ${{ steps.diffCollector.outputs.needs_osl }}
 
     steps:
     - name: Checkout Repo
@@ -22,23 +22,21 @@ jobs:
         git diff v2.5.0..HEAD -- collector/go.mod | grep -e '^+\s' | awk '{print $2}' | sort > additions.txt
         git diff v2.5.0..HEAD -- collector/go.mod | grep -e '^-\s' | awk '{print $2}' | sort > removals.txt
         
-        echo "Diffs:"
-        cat additions.txt
-        cat removals.txt
+        # exit code is "1" if there is a diff
+        diff removals.txt additions.txt > diff_of_diffs.txt
         
-        diff removals.txt additions.txt > $GITHUB_OUTPUT
+        # take exit code ("$?") and use it to output whether we need OSL
+        ([ $? -eq 1 ] && echo 'needs_osl=true' || echo 'needs_osl=false') > "$GITHUB_OUTPUT"
 
 #  test_outputs:
 #    runs-on: ubuntu-latest
 #    needs: check_go_mods
 #    steps:
     - name: Comment
+      if: steps.diffCollector.outputs.needs_osl == 'true'
       run: |
         echo '🚨 Warning: merging this PR will require a new OSL request! See diff below. 🚨'
-        echo "${{needs.diffCollector.outputs.diff_of_diffs}}"
-        
-        echo 'or...'
-        echo "${{steps.diffCollector.outputs}}"
+        cat diff_of_diffs.txt
 
 #  comment_osl_warning:
 #    runs-on: ubuntu-latest
